SELECT INS.ANIMAL_ID, INS.NAME
# , DATEDIFF(OUTS.DATETIME, INS.DATETIME) AS TERM
FROM ANIMAL_INS AS INS
INNER JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY DATEDIFF(OUTS.DATETIME, INS.DATETIME) DESC
LIMIT 2