SELECT CONCAT('/home/grep/src/',FILE.BOARD_ID,'/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS BOARD
INNER JOIN USED_GOODS_FILE AS FILE
ON BOARD.BOARD_ID = FILE.BOARD_ID
WHERE (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD) = VIEWS
ORDER BY FILE.FILE_ID DESC